### ISSUE TITLE
Timer2

### ISSUE THREAD

**Issue by isadoza03** [stevenvo/PulseSensor_Teensy3.2#1]
How did you get Timer2 to work with Teensy 3.2? It always gives me these errors:

Interrupt:28: error: expected constructor, destructor, or type conversion before '(' token
ISR(TIMER2_COMPA_vect){
^
In function 'void interruptSetup()':
Interrupt:18: error: 'TCCR2A' was not declared in this scope
TCCR2A = 0x02;
^
Interrupt:19: error: 'TCCR2B' was not declared in this scope
TCCR2B = 0x06;
^
Interrupt:20: error: 'OCR2A' was not declared in this scope
OCR2A = 0X7C;
^
Interrupt:21: error: 'TIMSK2' was not declared in this scope
TIMSK2 = 0x02;
^

At global scope:
Interrupt:28: error: expected constructor, destructor, or type conversion before '(' token
ISR(TIMER2_COMPA_vect){
^
exit status 1
expected constructor, destructor, or type conversion before '(' token

**Comment by krlash** [comment]
I don't think he did

**Comment by BubbaGumpLife** [comment]
Did you ever get this to work?  I get exactly the same errors

**Comment by h20180179** [comment]
same problem here
